<?php

namespace Rhubarb\Scaffolds\SocialLogin\Facebook\Leaves;

use Rhubarb\Scaffolds\SocialLogin\Leaves\Controls\SocialLoginButtonView;

class FacebookLoginButtonView extends SocialLoginButtonView
{
    /** @var FacebookLoginButtonModel $model * */
    protected $model;

    public function printViewContent()
    {
        print $this->model->facebookSdkScript;
        $this->model->addCssClassNames('c-button', 'c-button--large', 'c-button--long', 'c-button--secondary', 'facebook-login-button');
        parent::printViewContent(); // TODO: Change the autogenerated stub
    }

    public function getDeploymentPackage()
    {
        return new LeafDeploymentPackage(__DIR__ . '/FacebookLoginButtonViewBridge.js');
    }

    protected function getViewBridgeName()
    {
        return 'FacebookLoginButtonViewBridge';
    }
}
