<?php

namespace Rhubarb\Scaffolds\SocialLogin\Facebook\Leaves;


use Rhubarb\Leaf\Leaves\LeafDeploymentPackage;
use Rhubarb\Scaffolds\SocialLogin\Leaves\Controls\SocialLoginButtonView;

class FacebookLoginButtonView extends SocialLoginButtonView
{
    /** @var FacebookLoginButtonModel $model * */
    protected $model;

    public function printViewContent()
    {
        print $this->model->facebookSdkScript;
        $this->model->addCssClassNames('c-button', 'c-button--login-facebook');
        parent::printViewContent(); // TODO: Change the autogenerated stub
    }

    public function getDeploymentPackage()
    {
        $package = parent::getDeploymentPackage();
        $package->resourcesToDeploy[] = __DIR__ . '/FacebookLoginButtonViewBridge.js';
        return $package;
    }

    protected function getViewBridgeName()
    {
        return 'FacebookLoginButtonViewBridge';
    }
}
